### ISSUE TITLE
New syntax

### ISSUE THREAD

**Issue by Keitalith** [dasezo/dasezo-dark#1]
Hello, I'm one of the old users of your theme and I loved its syntax very much, I have never seen syntax better than this one BUT!
The most recent syntax update just ruined it completely, at least for TypeScript in which I do my projects.

Just look on the attached screenshots below and you'll see the clear difference and I think that you'll agree with me that it became worse.
New:
![image-6.png](https://github.com/dasezo/dasezo-dark/assets/70456337/e762287c-015e-4b8d-9c92-5caa78d7ce22)
Old (I used your theme's syntax for my own yet in development process theme):
![image-7.png](https://github.com/dasezo/dasezo-dark/assets/70456337/9b9f0a51-31b4-4943-a707-2579a2b4f69e)

**Comment by dasezo** [comment]
Hello Kito.
I really do appreciate you using my theme. and to be honest i do agree
with you about the syntax.
I will add the old syntax as an option for the theme as soon as possible.
Thank you ^^>
